version: '3'

services:
  etcd:
    image: soyking/etcd-goreman:3.2.7
    environment:
      - CLIENT_ADDR=etcd
  web_etcd:
    image: nanopony/web_etcd
    volumes:
      - ./conf/config.docker.ini:/app/conf/config.default.ini
    ports:
      - "8080:8080"
    depends_on:
      - etcd
